"""### feat: Add `user` and `user_visa` table to Models

35 min

- [x]  User table
    - [x]  id as p.k.
    - [x]  email
    - [x]  visas as backref from many2many
    - [x]  serialize method
- [x]  user_visa table (m2m)
    - [x]  user.id
    - [x]  visa.id
- [x]  flask db migrate

Revision ID: 0a36e6bdf4cd
Revises: 1f46f229c51c
Create Date: 2020-09-20 10:19:39.457158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a36e6bdf4cd'
down_revision = '1f46f229c51c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_visa',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('visa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['visa_id'], ['visa.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'visa_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_visa')
    op.drop_table('user')
    # ### end Alembic commands ###
