"""Remove unnecessary column from `visa`

Revision ID: 1f46f229c51c
Revises: c2abc1bccde4
Create Date: 2020-09-14 17:34:48.696318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f46f229c51c'
down_revision = 'c2abc1bccde4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visa', 'some_string')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visa', sa.Column('some_string', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
